import { KoAdjective, KoVerb } from './types';

/**
 * 동사·형용사 사전.
 *
 * 한국어 활용을 형태소 분석으로 풀지 않는다. 대신 **과거형 어간**을 적어 두고
 * 어미(어/어요/다/음/습니다…)를 붙여 표면형을 만든다. "갔" + 어요 → 갔어요.
 * 분석기를 넣는 것보다 정확하고, 무엇보다 무엇을 못 알아듣는지가 눈에 보인다.
 */

/** 과거형 어간 뒤에 올 수 있는 어미 */
export const PAST_ENDINGS = ['어요', '어', '다', '음', '습니다', '네요', '네', '고', '는데', '지만'];

export const VERBS: KoVerb[] = [
  {
    id: 'go',
    ko: '가다',
    pastStem: '갔',
    presentForms: ['가요', '간다', '가'],
    futureStems: ['갈 거', '가려고', '갈래'],
    en: { past: 'went', present: 'go', base: 'go' },
    ja: { past: '行きました', present: '行きます' },
    frame: 'go',
  },
  {
    id: 'visit',
    ko: '다녀오다',
    pastStem: '다녀왔',
    presentForms: ['다녀와요', '다녀온다'],
    futureStems: ['다녀올 거'],
    en: { past: 'went', present: 'go', base: 'go' },
    ja: { past: '行ってきました', present: '行ってきます' },
    frame: 'go',
  },
  {
    id: 'come',
    ko: '오다',
    pastStem: '왔',
    presentForms: ['와요', '온다'],
    futureStems: ['올 거'],
    en: { past: 'came', present: 'come', base: 'come' },
    ja: { past: '来ました', present: '来ます' },
    frame: 'intransitive',
  },
  {
    id: 'eat',
    ko: '먹다',
    pastStem: '먹었',
    presentForms: ['먹어요', '먹는다', '먹어'],
    futureStems: ['먹을 거', '먹으려고'],
    en: { past: 'ate', present: 'eat', base: 'eat' },
    ja: { past: '食べました', present: '食べます' },
    frame: 'transitive',
  },
  {
    id: 'drink',
    ko: '마시다',
    pastStem: '마셨',
    presentForms: ['마셔요', '마신다', '마셔'],
    futureStems: ['마실 거'],
    en: { past: 'drank', present: 'drink', base: 'drink' },
    ja: { past: '飲みました', present: '飲みます' },
    frame: 'transitive',
  },
  {
    id: 'meet',
    ko: '만나다',
    pastStem: '만났',
    presentForms: ['만나요', '만난다', '만나'],
    futureStems: ['만날 거', '만나려고'],
    en: { past: 'met', present: 'meet', base: 'meet' },
    ja: { past: '会いました', present: '会います' },
    frame: 'meet',
  },
  {
    id: 'watch',
    ko: '보다',
    pastStem: '봤',
    presentForms: ['봐요', '본다', '봐'],
    futureStems: ['볼 거', '보려고'],
    en: { past: 'watched', present: 'watch', base: 'watch' },
    ja: { past: '見ました', present: '見ます' },
    frame: 'transitive',
  },
  {
    id: 'read',
    ko: '읽다',
    pastStem: '읽었',
    presentForms: ['읽어요', '읽는다', '읽어'],
    futureStems: ['읽을 거'],
    en: { past: 'read', present: 'read', base: 'read' },
    ja: { past: '読みました', present: '読みます' },
    frame: 'transitive',
  },
  {
    id: 'listen',
    ko: '듣다',
    pastStem: '들었',
    presentForms: ['들어요', '듣는다'],
    futureStems: ['들을 거'],
    en: { past: 'listened to', present: 'listen to', base: 'listen to' },
    ja: { past: '聞きました', present: '聞きます' },
    frame: 'transitive',
  },
  {
    id: 'buy',
    ko: '사다',
    pastStem: '샀',
    presentForms: ['사요', '산다'],
    futureStems: ['살 거', '사려고'],
    en: { past: 'bought', present: 'buy', base: 'buy' },
    ja: { past: '買いました', present: '買います' },
    frame: 'transitive',
  },
  {
    id: 'make',
    ko: '만들다',
    pastStem: '만들었',
    presentForms: ['만들어요', '만든다'],
    futureStems: ['만들 거'],
    en: { past: 'made', present: 'make', base: 'make' },
    ja: { past: '作りました', present: '作ります' },
    frame: 'transitive',
  },
  {
    id: 'sleep',
    ko: '자다',
    pastStem: '잤',
    presentForms: ['자요', '잔다'],
    futureStems: ['잘 거'],
    en: { past: 'slept', present: 'sleep', base: 'sleep' },
    ja: { past: '寝ました', present: '寝ます' },
    frame: 'intransitive',
  },
  {
    id: 'wake',
    ko: '일어나다',
    pastStem: '일어났',
    presentForms: ['일어나요', '일어난다'],
    futureStems: ['일어날 거'],
    en: { past: 'woke up', present: 'wake up', base: 'wake up' },
    ja: { past: '起きました', present: '起きます' },
    frame: 'intransitive',
  },
  {
    id: 'walk',
    ko: '걷다',
    pastStem: '걸었',
    presentForms: ['걸어요', '걷는다'],
    futureStems: ['걸을 거'],
    en: { past: 'walked', present: 'walk', base: 'walk' },
    ja: { past: '歩きました', present: '歩きます' },
    frame: 'intransitive',
  },
  {
    id: 'rest',
    ko: '쉬다',
    pastStem: '쉬었',
    presentForms: ['쉬어요', '쉰다'],
    futureStems: ['쉴 거'],
    en: { past: 'rested', present: 'rest', base: 'rest' },
    ja: { past: '休みました', present: '休みます' },
    frame: 'intransitive',
  },
  {
    id: 'laugh',
    ko: '웃다',
    pastStem: '웃었',
    presentForms: ['웃어요', '웃는다'],
    futureStems: ['웃을 거'],
    en: { past: 'laughed', present: 'laugh', base: 'laugh' },
    ja: { past: '笑いました', present: '笑います' },
    frame: 'intransitive',
  },
  {
    id: 'cry',
    ko: '울다',
    pastStem: '울었',
    presentForms: ['울어요', '운다'],
    futureStems: ['울 거'],
    en: { past: 'cried', present: 'cry', base: 'cry' },
    ja: { past: '泣きました', present: '泣きます' },
    frame: 'intransitive',
  },
  {
    id: 'hangout',
    ko: '놀다',
    pastStem: '놀았',
    presentForms: ['놀아요', '논다'],
    futureStems: ['놀 거'],
    en: { past: 'hung out', present: 'hang out', base: 'hang out' },
    ja: { past: '遊びました', present: '遊びます' },
    frame: 'intransitive',
  },
  {
    id: 'wait',
    ko: '기다리다',
    pastStem: '기다렸',
    presentForms: ['기다려요', '기다린다'],
    futureStems: ['기다릴 거'],
    en: { past: 'waited for', present: 'wait for', base: 'wait for' },
    ja: { past: '待ちました', present: '待ちます' },
    frame: 'transitive',
  },
  {
    id: 'finish',
    ko: '끝내다',
    pastStem: '끝냈',
    presentForms: ['끝내요', '끝낸다'],
    futureStems: ['끝낼 거'],
    en: { past: 'finished', present: 'finish', base: 'finish' },
    ja: { past: '終えました', present: '終えます' },
    frame: 'transitive',
  },
  {
    id: 'learn',
    ko: '배우다',
    pastStem: '배웠',
    presentForms: ['배워요', '배운다'],
    futureStems: ['배울 거'],
    en: { past: 'learned', present: 'learn', base: 'learn' },
    ja: { past: '習いました', present: '習います' },
    frame: 'transitive',
  },
  {
    id: 'find',
    ko: '찾다',
    pastStem: '찾았',
    presentForms: ['찾아요', '찾는다'],
    futureStems: ['찾을 거'],
    en: { past: 'looked for', present: 'look for', base: 'look for' },
    ja: { past: '探しました', present: '探します' },
    frame: 'transitive',
  },
  {
    id: 'like',
    ko: '좋아하다',
    pastStem: '좋아했',
    presentForms: ['좋아해요', '좋아한다', '좋아해'],
    futureStems: ['좋아할 거'],
    en: { past: 'liked', present: 'like', base: 'like' },
    ja: { past: '好きでした', present: '好きです' },
    frame: 'transitive',
  },
  {
    id: 'send',
    ko: '보내다',
    pastStem: '보냈',
    presentForms: ['보내요', '보낸다'],
    futureStems: ['보낼 거'],
    en: { past: 'sent', present: 'send', base: 'send' },
    ja: { past: '送りました', present: '送ります' },
    frame: 'transitive',
  },
  {
    id: 'take-photo',
    ko: '찍다',
    pastStem: '찍었',
    presentForms: ['찍어요', '찍는다'],
    futureStems: ['찍을 거'],
    en: { past: 'took', present: 'take', base: 'take' },
    ja: { past: '撮りました', present: '撮ります' },
    frame: 'transitive',
  },
  {
    id: 'wash',
    ko: '씻다',
    pastStem: '씻었',
    presentForms: ['씻어요', '씻는다'],
    futureStems: ['씻을 거'],
    en: { past: 'washed up', present: 'wash up', base: 'wash up' },
    ja: { past: '洗いました', present: '洗います' },
    frame: 'intransitive',
  },
  {
    id: 'arrive',
    ko: '도착하다',
    pastStem: '도착했',
    presentForms: ['도착해요', '도착한다'],
    futureStems: ['도착할 거'],
    en: { past: 'arrived', present: 'arrive', base: 'arrive' },
    ja: { past: '着きました', present: '着きます' },
    frame: 'intransitive',
  },
  {
    id: 'scolded',
    ko: '혼나다',
    pastStem: '혼났',
    presentForms: ['혼나요'],
    futureStems: ['혼날 거'],
    en: { past: 'got in trouble', present: 'get in trouble', base: 'get in trouble' },
    ja: { past: '怒られました', present: '怒られます' },
    frame: 'intransitive',
  },
  {
    // '하다'는 마지막에 둔다. '운동했어'는 명사+하다 표(DO_VERBS)가 먼저 잡아야 한다.
    id: 'do',
    ko: '하다',
    pastStem: '했',
    presentForms: ['해요', '한다'],
    futureStems: ['할 거'],
    en: { past: 'did', present: 'do', base: 'do' },
    ja: { past: 'しました', present: 'します' },
    frame: 'transitive',
  },
  {
    id: 'start',
    ko: '시작하다',
    pastStem: '시작했',
    presentForms: ['시작해요', '시작한다'],
    futureStems: ['시작할 거'],
    en: { past: 'started', present: 'start', base: 'start' },
    ja: { past: '始めました', present: '始めます' },
    frame: 'transitive',
  },
];

/**
 * '명사 + 하다' 동사 (공부했어 / 운동했어 …).
 *
 * 하다 동사는 앞의 명사만 갈아 끼우면 되므로 따로 둔다. 여기 있는 명사는
 * '했/해요/한다' 앞에 붙어 있을 때만 동사로 본다.
 */
export const DO_VERBS: { ko: string; en: { past: string; present: string }; ja: { past: string; present: string } }[] = [
  { ko: '공부', en: { past: 'studied', present: 'study' }, ja: { past: '勉強しました', present: '勉強します' } },
  { ko: '운동', en: { past: 'worked out', present: 'work out' }, ja: { past: '運動しました', present: '運動します' } },
  { ko: '일', en: { past: 'worked', present: 'work' }, ja: { past: '仕事しました', present: '仕事します' } },
  { ko: '요리', en: { past: 'cooked', present: 'cook' }, ja: { past: '料理しました', present: '料理します' } },
  { ko: '청소', en: { past: 'cleaned', present: 'clean' }, ja: { past: '掃除しました', present: '掃除します' } },
  { ko: '빨래', en: { past: 'did the laundry', present: 'do the laundry' }, ja: { past: '洗濯しました', present: '洗濯します' } },
  { ko: '산책', en: { past: 'took a walk', present: 'take a walk' }, ja: { past: '散歩しました', present: '散歩します' } },
  { ko: '전화', en: { past: 'made a call', present: 'make a call' }, ja: { past: '電話しました', present: '電話します' } },
  { ko: '이야기', en: { past: 'talked', present: 'talk' }, ja: { past: '話しました', present: '話します' } },
  { ko: '얘기', en: { past: 'talked', present: 'talk' }, ja: { past: '話しました', present: '話します' } },
  { ko: '쇼핑', en: { past: 'went shopping', present: 'go shopping' }, ja: { past: '買い物しました', present: '買い物します' } },
  { ko: '운전', en: { past: 'drove', present: 'drive' }, ja: { past: '運転しました', present: '運転します' } },
  { ko: '연습', en: { past: 'practiced', present: 'practice' }, ja: { past: '練習しました', present: '練習します' } },
  { ko: '준비', en: { past: 'got ready', present: 'get ready' }, ja: { past: '準備しました', present: '準備します' } },
  { ko: '생각', en: { past: 'thought about it', present: 'think about it' }, ja: { past: '考えました', present: '考えます' } },

  /* --- 도메인별 실사용 문장에서 뽑아 검증한 활동 --- */
  { ko: '출근', en: { past: 'went to work', present: 'go to work' }, ja: { past: '出勤しました', present: '出勤します' } },
  { ko: '퇴근', en: { past: 'got off work', present: 'get off work' }, ja: { past: '退勤しました', present: '退勤します' } },
  { ko: '야근', en: { past: 'worked late', present: 'work late' }, ja: { past: '残業しました', present: '残業します' } },
  { ko: '회의', en: { past: 'had a meeting', present: 'have a meeting' }, ja: { past: '会議しました', present: '会議します' } },
  { ko: '미팅', en: { past: 'had a meeting', present: 'have a meeting' }, ja: { past: '打ち合わせしました', present: '打ち合わせします' } },
  { ko: '발표', en: { past: 'gave a presentation', present: 'give a presentation' }, ja: { past: '発表しました', present: '発表します' } },
  { ko: '촬영', en: { past: 'had a shoot', present: 'have a shoot' }, ja: { past: '撮影しました', present: '撮影します' } },
  { ko: '편집', en: { past: 'did some editing', present: 'do some editing' }, ja: { past: '編集しました', present: '編集します' } },
  { ko: '알바', en: { past: 'worked a shift', present: 'work a shift' }, ja: { past: 'バイトしました', present: 'バイトします' } },
  { ko: '회식', en: { past: 'had a work dinner', present: 'have a work dinner' }, ja: { past: '飲み会に行きました', present: '飲み会に行きます' } },
  { ko: '재택근무', en: { past: 'worked from home', present: 'work from home' }, ja: { past: '在宅勤務しました', present: '在宅勤務します' } },
  { ko: '지각', en: { past: 'showed up late', present: 'show up late' }, ja: { past: '遅刻しました', present: '遅刻します' } },
  { ko: '조퇴', en: { past: 'left work early', present: 'leave work early' }, ja: { past: '早退しました', present: '早退します' } },
  { ko: '실수', en: { past: 'made a mistake', present: 'make a mistake' }, ja: { past: 'ミスしました', present: 'ミスします' } },
  { ko: '퇴사', en: { past: 'quit my job', present: 'quit my job' }, ja: { past: '退職しました', present: '退職します' } },
  { ko: '이직', en: { past: 'changed jobs', present: 'change jobs' }, ja: { past: '転職しました', present: '転職します' } },
  { ko: '입사', en: { past: 'started a new job', present: 'start a new job' }, ja: { past: '入社しました', present: '入社します' } },
  { ko: '승진', en: { past: 'got promoted', present: 'get promoted' }, ja: { past: '昇進しました', present: '昇進します' } },
  { ko: '통화', en: { past: 'talked on the phone', present: 'talk on the phone' }, ja: { past: '電話で話しました', present: '電話で話します' } },
  { ko: '면접', en: { past: 'had an interview', present: 'have an interview' }, ja: { past: '面接を受けました', present: '面接を受けます' } },
  { ko: '수정', en: { past: 'made some edits', present: 'make some edits' }, ja: { past: '修正しました', present: '修正します' } },
  { ko: '설거지', en: { past: 'did the dishes', present: 'do the dishes' }, ja: { past: '皿洗いしました', present: '皿洗いします' } },
  { ko: '정리', en: { past: 'tidied up', present: 'tidy up' }, ja: { past: '片付けました', present: '片付けます' } },
  { ko: '대청소', en: { past: 'did a deep clean', present: 'do a deep clean' }, ja: { past: '大掃除しました', present: '大掃除します' } },
  { ko: '분리수거', en: { past: 'sorted the recycling', present: 'sort the recycling' }, ja: { past: '分別しました', present: '分別します' } },
  { ko: '이사', en: { past: 'moved', present: 'move' }, ja: { past: '引っ越しました', present: '引っ越します' } },
  { ko: '예약', en: { past: 'made an appointment', present: 'make an appointment' }, ja: { past: '予約しました', present: '予約します' } },
  { ko: '주문', en: { past: 'placed an order', present: 'place an order' }, ja: { past: '注文しました', present: '注文します' } },
  { ko: '결제', en: { past: 'paid', present: 'pay' }, ja: { past: '支払いました', present: '支払います' } },
  { ko: '환불', en: { past: 'got a refund', present: 'get a refund' }, ja: { past: '返金してもらいました', present: '返金してもらいます' } },
  { ko: '반품', en: { past: 'returned it', present: 'return it' }, ja: { past: '返品しました', present: '返品します' } },
  { ko: '송금', en: { past: 'transferred money', present: 'transfer money' }, ja: { past: '送金しました', present: '送金します' } },
  { ko: '신청', en: { past: 'applied for it', present: 'apply for it' }, ja: { past: '申し込みました', present: '申し込みます' } },
  { ko: '계약', en: { past: 'signed the contract', present: 'sign the contract' }, ja: { past: '契約しました', present: '契約します' } },
  { ko: '수리', en: { past: 'got it fixed', present: 'get it fixed' }, ja: { past: '修理してもらいました', present: '修理してもらいます' } },
  { ko: '설치', en: { past: 'got it installed', present: 'get it installed' }, ja: { past: '設置してもらいました', present: '設置してもらいます' } },
  { ko: '취소', en: { past: 'canceled it', present: 'cancel it' }, ja: { past: 'キャンセルしました', present: 'キャンセルします' } },
  { ko: '세차', en: { past: 'washed the car', present: 'wash the car' }, ja: { past: '洗車しました', present: '洗車します' } },
  { ko: '염색', en: { past: 'dyed my hair', present: 'dye my hair' }, ja: { past: '髪を染めました', present: '髪を染めます' } },
  { ko: '파마', en: { past: 'got a perm', present: 'get a perm' }, ja: { past: 'パーマをかけました', present: 'パーマをかけます' } },
  { ko: '커트', en: { past: 'got a haircut', present: 'get a haircut' }, ja: { past: '髪を切りました', present: '髪を切ります' } },
  { ko: '건강검진', en: { past: 'had a checkup', present: 'have a checkup' }, ja: { past: '健康診断を受けました', present: '健康診断を受けます' } },
  { ko: '시험공부', en: { past: 'studied for the exam', present: 'study for the exam' }, ja: { past: '試験勉強しました', present: '試験勉強します' } },
  { ko: '과제', en: { past: 'did my assignment', present: 'do my assignment' }, ja: { past: '課題をやりました', present: '課題をやります' } },
  { ko: '제출', en: { past: 'turned it in', present: 'turn it in' }, ja: { past: '提出しました', present: '提出します' } },
  { ko: '복습', en: { past: 'reviewed my notes', present: 'review my notes' }, ja: { past: '復習しました', present: '復習します' } },
  { ko: '필기', en: { past: 'took notes', present: 'take notes' }, ja: { past: 'ノートを取りました', present: 'ノートを取ります' } },
  { ko: '벼락치기', en: { past: 'crammed', present: 'cram' }, ja: { past: '一夜漬けしました', present: '一夜漬けします' } },
  { ko: '결석', en: { past: 'missed class', present: 'miss class' }, ja: { past: '欠席しました', present: '欠席します' } },
  { ko: '수강신청', en: { past: 'signed up for classes', present: 'sign up for classes' }, ja: { past: '履修登録しました', present: '履修登録します' } },
  { ko: '합격', en: { past: 'passed', present: 'pass' }, ja: { past: '合格しました', present: '合格します' } },
  { ko: '졸업', en: { past: 'graduated', present: 'graduate' }, ja: { past: '卒業しました', present: '卒業します' } },
  { ko: '스터디', en: { past: 'had a study group', present: 'have a study group' }, ja: { past: '勉強会をしました', present: '勉強会をします' } },
  { ko: '질문', en: { past: 'asked a question', present: 'ask a question' }, ja: { past: '質問しました', present: '質問します' } },
  { ko: '집중', en: { past: 'focused', present: 'focus' }, ja: { past: '集中しました', present: '集中します' } },
  { ko: '여행', en: { past: 'went on a trip', present: 'go on a trip' }, ja: { past: '旅行しました', present: '旅行します' } },
  { ko: '구경', en: { past: 'looked around', present: 'look around' }, ja: { past: '見て回りました', present: '見て回ります' } },
  { ko: '외출', en: { past: 'went out', present: 'go out' }, ja: { past: '外出しました', present: '外出します' } },
  { ko: '등산', en: { past: 'went hiking', present: 'go hiking' }, ja: { past: '登山しました', present: '登山します' } },
  { ko: '캠핑', en: { past: 'went camping', present: 'go camping' }, ja: { past: 'キャンプしました', present: 'キャンプします' } },
  { ko: '드라이브', en: { past: 'went for a drive', present: 'go for a drive' }, ja: { past: 'ドライブしました', present: 'ドライブします' } },
  { ko: '데이트', en: { past: 'went on a date', present: 'go on a date' }, ja: { past: 'デートしました', present: 'デートします' } },
  { ko: '예매', en: { past: 'booked a ticket', present: 'book a ticket' }, ja: { past: 'チケットを取りました', present: 'チケットを取ります' } },
  { ko: '체크인', en: { past: 'checked in', present: 'check in' }, ja: { past: 'チェックインしました', present: 'チェックインします' } },
  { ko: '출장', en: { past: 'went on a business trip', present: 'go on a business trip' }, ja: { past: '出張しました', present: '出張します' } },
  { ko: '외식', en: { past: 'ate out', present: 'eat out' }, ja: { past: '外食しました', present: '外食します' } },
  { ko: '혼밥', en: { past: 'ate alone', present: 'eat alone' }, ja: { past: '一人で食べました', present: '一人で食べます' } },
  { ko: '과식', en: { past: 'overate', present: 'overeat' }, ja: { past: '食べすぎました', present: '食べすぎます' } },
  { ko: '포장', en: { past: 'got it to go', present: 'get it to go' }, ja: { past: '持ち帰りにしました', present: '持ち帰りにします' } },
  { ko: '계산', en: { past: 'paid', present: 'pay' }, ja: { past: '払いました', present: '払います' } },
  { ko: '웨이팅', en: { past: 'waited in line', present: 'wait in line' }, ja: { past: '並びました', present: '並びます' } },
  { ko: '다이어트', en: { past: 'went on a diet', present: 'go on a diet' }, ja: { past: 'ダイエットしました', present: 'ダイエットします' } },
  { ko: '더치페이', en: { past: 'split the bill', present: 'split the bill' }, ja: { past: '割り勘にしました', present: '割り勘にします' } },
  { ko: '샤워', en: { past: 'took a shower', present: 'take a shower' }, ja: { past: 'シャワーを浴びました', present: 'シャワーを浴びます' } },
  { ko: '화해', en: { past: 'made up', present: 'make up' }, ja: { past: '仲直りしました', present: '仲直りします' } },
  { ko: '후회', en: { past: 'regretted it', present: 'regret it' }, ja: { past: '後悔しました', present: '後悔します' } },
  { ko: '고민', en: { past: 'thought it over', present: 'think it over' }, ja: { past: '悩みました', present: '悩みます' } },
];

/**
 * 형용사의 ja는 **정중한 과거형 한 덩어리**로 적는다 (疲れました / 楽しかったです).
 * 일본어는 형용사 종류(い·な)마다 과거형이 달라서, 어간만 두고 조합하려 하면 틀린다.
 */
const adj = (ko: string, forms: string[], en: string, ja: string, subject: KoAdjective['subject'] = 'i'): KoAdjective => ({
  ko,
  forms,
  en,
  ja,
  subject,
});

export const ADJECTIVES: KoAdjective[] = [
  adj('피곤하다', ['피곤해요', '피곤했어요', '피곤했어', '피곤해', '피곤하다', '피곤했다'], 'tired', '疲れました'),
  adj('행복하다', ['행복해요', '행복했어요', '행복했어', '행복해', '행복하다'], 'happy', '幸せでした'),
  adj('슬프다', ['슬퍼요', '슬펐어요', '슬펐어', '슬퍼', '슬프다'], 'sad', '悲しかったです'),
  adj('기쁘다', ['기뻐요', '기뻤어요', '기뻤어', '기뻐'], 'glad', 'うれしかったです'),
  adj('신나다', ['신나요', '신났어요', '신났어', '신나'], 'excited', 'わくわくしました'),
  adj('화나다', ['화나요', '화났어요', '화났어', '화나'], 'upset', '怒りました'),
  adj('긴장되다', ['긴장돼요', '긴장됐어요', '긴장됐어', '긴장돼'], 'nervous', '緊張しました'),
  adj('바쁘다', ['바빠요', '바빴어요', '바빴어', '바빠', '바쁘다'], 'busy', '忙しかったです'),
  adj('심심하다', ['심심해요', '심심했어요', '심심했어', '심심해'], 'bored', '退屈でした'),
  adj('배고프다', ['배고파요', '배고팠어요', '배고팠어', '배고파'], 'hungry', 'お腹がすきました'),
  adj('괜찮다', ['괜찮아요', '괜찮았어요', '괜찮았어', '괜찮아'], 'okay', '大丈夫でした'),
  adj('힘들다', ['힘들어요', '힘들었어요', '힘들었어', '힘들어', '힘들다'], 'hard', '大変でした', 'it'),
  adj('좋다', ['좋아요', '좋았어요', '좋았어', '좋아', '좋다'], 'good', 'よかったです', 'it'),
  adj('재미있다', ['재미있어요', '재미있었어요', '재밌었어', '재밌어', '재미있어', '재미있다'], 'fun', '楽しかったです', 'it'),
  adj('맛있다', ['맛있어요', '맛있었어요', '맛있었어', '맛있어', '맛있다'], 'delicious', 'おいしかったです', 'it'),
  adj('덥다', ['더워요', '더웠어요', '더웠어', '더워', '덥다'], 'hot', '暑かったです', 'it'),
  adj('춥다', ['추워요', '추웠어요', '추웠어', '추워', '춥다'], 'cold', '寒かったです', 'it'),
  adj('어렵다', ['어려워요', '어려웠어요', '어려웠어', '어려워'], 'difficult', '難しかったです', 'it'),
  adj('쉽다', ['쉬워요', '쉬웠어요', '쉬웠어', '쉬워'], 'easy', '簡単でした', 'it'),
  adj('예쁘다', ['예뻐요', '예뻤어요', '예뻤어', '예뻐'], 'pretty', 'きれいでした', 'it'),
  adj('조용하다', ['조용해요', '조용했어요', '조용했어', '조용해'], 'quiet', '静かでした', 'it'),
  adj('시끄럽다', ['시끄러워요', '시끄러웠어요', '시끄러웠어', '시끄러워'], 'noisy', 'うるさかったです', 'it'),

  /* --- 도메인별 실사용 문장에서 뽑아 검증한 형용사 --- */
  adj('짜증나다', ['짜증나요', '짜증났어요', '짜증났어', '짜증나', '짜증난다', '짜증났다'], 'annoyed', 'イライラしました'),
  adj('답답하다', ['답답해요', '답답했어요', '답답했어', '답답해', '답답하다', '답답했다'], 'frustrated', 'もどかしかったです'),
  adj('정신없다', ['정신없어요', '정신없었어요', '정신없었어', '정신없어', '정신없다'], 'hectic', 'バタバタしました', 'it'),
  adj('뿌듯하다', ['뿌듯해요', '뿌듯했어요', '뿌듯했어', '뿌듯해', '뿌듯하다'], 'proud of myself', '誇らしかったです'),
  adj('부담되다', ['부담돼요', '부담됐어요', '부담됐어', '부담돼'], 'under pressure', 'プレッシャーを感じました'),
  adj('억울하다', ['억울해요', '억울했어요', '억울했어', '억울해'], 'unfair', '悔しかったです', 'it'),
  adj('지치다', ['지쳐요', '지쳤어요', '지쳤어', '지쳐', '지친다'], 'worn out', 'へとへとでした'),
  adj('빡세다', ['빡세요', '빡셌어요', '빡셌어', '빡세', '빡셌다'], 'rough', 'きつかったです', 'it'),
  adj('졸리다', ['졸려요', '졸렸어요', '졸렸어', '졸려'], 'sleepy', '眠かったです'),
  adj('후련하다', ['후련해요', '후련했어요', '후련했어', '후련해'], 'relieved', 'すっきりしました'),
  adj('불안하다', ['불안해요', '불안했어요', '불안했어', '불안해'], 'anxious', '不安でした'),
  adj('창피하다', ['창피해요', '창피했어요', '창피했어', '창피해'], 'embarrassed', '恥ずかしかったです'),
  adj('어색하다', ['어색해요', '어색했어요', '어색했어', '어색해'], 'awkward', '気まずかったです', 'it'),
  adj('귀찮다', ['귀찮아요', '귀찮았어요', '귀찮았어', '귀찮아', '귀찮다', '귀찮았다'], 'lazy', '面倒でした'),
  adj('아프다', ['아파요', '아팠어요', '아팠어', '아파', '아프다', '아팠다'], 'sick', '具合が悪かったです'),
  adj('개운하다', ['개운해요', '개운했어요', '개운했어', '개운해'], 'refreshed', 'すっきりしました'),
  adj('비싸다', ['비싸요', '비쌌어요', '비쌌어', '비싸', '비싸다'], 'expensive', '高かったです', 'it'),
  adj('깨끗하다', ['깨끗해요', '깨끗했어요', '깨끗했어', '깨끗해', '깨끗하다'], 'clean', 'きれいでした', 'it'),
  adj('지저분하다', ['지저분해요', '지저분했어요', '지저분했어', '지저분해'], 'messy', '散らかっていました', 'it'),
  adj('걱정되다', ['걱정돼요', '걱정됐어요', '걱정됐어', '걱정돼', '걱정된다'], 'worried', '心配でした'),
  adj('홀가분하다', ['홀가분해요', '홀가분했어요', '홀가분했어', '홀가분해'], 'relieved', 'ほっとしました'),
  adj('헷갈리다', ['헷갈려요', '헷갈렸어요', '헷갈렸어', '헷갈려', '헷갈린다'], 'confused', '混乱しました'),
  adj('실망하다', ['실망했어요', '실망했어', '실망했다', '실망해요'], 'disappointed', 'がっかりしました'),
  adj('지루하다', ['지루해요', '지루했어요', '지루했어', '지루해', '지루하다'], 'boring', '退屈でした', 'it'),
  adj('아쉽다', ['아쉬워요', '아쉬웠어요', '아쉬웠어', '아쉬워', '아쉽다'], 'disappointing', '残念でした', 'it'),
  adj('설레다', ['설레요', '설렜어요', '설렜어', '설레', '설렌다', '설레다'], 'excited for it', 'ドキドキしました'),
  adj('늦다', ['늦었어요', '늦었어', '늦어요', '늦었다', '늦어', '늦다'], 'late', '遅れました'),
  adj('막히다', ['막혔어요', '막혔어', '막혔다', '막혀요', '막혀'], 'stuck in traffic', '渋滞していました'),
  adj('여유롭다', ['여유로워요', '여유로웠어요', '여유로웠어', '여유로워', '여유롭다'], 'relaxed', 'のんびりしました'),
  adj('붐비다', ['붐벼요', '붐볐어요', '붐볐어', '붐볐다', '붐벼'], 'crowded', '混んでいました', 'it'),
  adj('멀다', ['멀어요', '멀었어요', '멀었어', '멀었다', '멀어', '멀다'], 'far', '遠かったです', 'it'),
  adj('가깝다', ['가까워요', '가까웠어요', '가까웠어', '가까워', '가깝다'], 'close', '近かったです', 'it'),
  adj('멋있다', ['멋있어요', '멋있었어요', '멋있었어', '멋있어', '멋졌어요', '멋졌어', '멋져요', '멋지다'], 'amazing', '素敵でした', 'it'),
  adj('신기하다', ['신기해요', '신기했어요', '신기했어', '신기해', '신기하다'], 'fascinating', '不思議でした', 'it'),
  adj('시원하다', ['시원해요', '시원했어요', '시원했어', '시원해', '시원하다'], 'refreshing', '涼しかったです', 'it'),
  adj('맵다', ['매워요', '매웠어요', '매웠어', '매워', '맵다', '매웠다'], 'spicy', '辛かったです', 'it'),
  adj('배부르다', ['배불러요', '배불렀어요', '배불렀어', '배불러', '배부르다', '배불렀다'], 'full', 'お腹いっぱいでした'),
  adj('취하다', ['취했어요', '취했어', '취했다', '취해요', '취해'], 'drunk', '酔いました'),
  adj('짜다', ['짜요', '짰어요', '짰어', '짰다'], 'salty', 'しょっぱかったです', 'it'),
  adj('달다', ['달아요', '달았어요', '달았어', '달아', '달다', '달았다'], 'sweet', '甘かったです', 'it'),
  adj('느끼하다', ['느끼해요', '느끼했어요', '느끼했어', '느끼해', '느끼하다'], 'greasy', '脂っこかったです', 'it'),
  adj('별로다', ['별로예요', '별로였어요', '별로였어', '별로야', '별로다', '별로였다'], 'disappointing', 'いまいちでした', 'it'),
  adj('맛없다', ['맛없어요', '맛없었어요', '맛없었어', '맛없어', '맛없다'], 'bad', 'おいしくなかったです', 'it'),
  adj('든든하다', ['든든해요', '든든했어요', '든든했어', '든든해'], 'filling', '食べごたえがありました', 'it'),
  adj('최고다', ['최고예요', '최고였어요', '최고였어', '최고야', '최고다'], 'amazing', '最高でした', 'it'),
  adj('신선하다', ['신선해요', '신선했어요', '신선했어', '신선해'], 'fresh', '新鮮でした', 'it'),
  adj('뜨겁다', ['뜨거워요', '뜨거웠어요', '뜨거웠어', '뜨거워', '뜨겁다'], 'hot', '熱かったです', 'it'),
  adj('바삭하다', ['바삭해요', '바삭했어요', '바삭했어', '바삭해'], 'crispy', 'サクサクでした', 'it'),
  adj('질리다', ['질려요', '질렸어요', '질렸어', '질려'], 'sick of it', '飽きました'),
  adj('우울하다', ['우울해요', '우울했어요', '우울했어', '우울해', '우울하다', '우울했다'], 'down', '落ち込みました'),
  adj('속상하다', ['속상해요', '속상했어요', '속상했어', '속상해', '속상하다'], 'upset', 'つらかったです'),
  adj('외롭다', ['외로워요', '외로웠어요', '외로웠어', '외로워', '외롭다'], 'lonely', 'さびしかったです'),
  adj('서운하다', ['서운해요', '서운했어요', '서운했어', '서운해', '서운하다'], 'hurt', 'がっかりしました'),
  adj('무섭다', ['무서워요', '무서웠어요', '무서웠어', '무서워', '무섭다'], 'scared', '怖かったです'),
  adj('고맙다', ['고마워요', '고마웠어요', '고마웠어', '고마워', '고맙다'], 'grateful', 'ありがたかったです'),
];
