import { KoAdjective, KoVerb } from './types';

/**
 * 동사·형용사 사전.
 *
 * 한국어 활용을 형태소 분석으로 풀지 않는다. 대신 **과거형 어간**을 적어 두고
 * 어미(어/어요/다/음/습니다…)를 붙여 표면형을 만든다. "갔" + 어요 → 갔어요.
 * 분석기를 넣는 것보다 정확하고, 무엇보다 무엇을 못 알아듣는지가 눈에 보인다.
 */

/** 과거형 어간 뒤에 올 수 있는 어미 */
export const PAST_ENDINGS = ['어요', '어', '다', '음', '습니다', '네요', '네', '고', '는데', '지만'];

export const VERBS: KoVerb[] = [
  {
    id: 'go',
    ko: '가다',
    pastStem: '갔',
    presentForms: ['가요', '간다', '가'],
    futureStems: ['갈 거', '가려고', '갈래'],
    en: { past: 'went', present: 'go', base: 'go' },
    ja: { past: '行きました', present: '行きます' },
    frame: 'go',
  },
  {
    id: 'visit',
    ko: '다녀오다',
    pastStem: '다녀왔',
    presentForms: ['다녀와요', '다녀온다'],
    futureStems: ['다녀올 거'],
    en: { past: 'went', present: 'go', base: 'go' },
    ja: { past: '行ってきました', present: '行ってきます' },
    frame: 'go',
  },
  {
    id: 'come',
    ko: '오다',
    pastStem: '왔',
    presentForms: ['와요', '온다'],
    futureStems: ['올 거'],
    en: { past: 'came', present: 'come', base: 'come' },
    ja: { past: '来ました', present: '来ます' },
    frame: 'intransitive',
  },
  {
    id: 'eat',
    ko: '먹다',
    pastStem: '먹었',
    presentForms: ['먹어요', '먹는다', '먹어'],
    futureStems: ['먹을 거', '먹으려고'],
    en: { past: 'ate', present: 'eat', base: 'eat' },
    ja: { past: '食べました', present: '食べます' },
    frame: 'transitive',
  },
  {
    id: 'drink',
    ko: '마시다',
    pastStem: '마셨',
    presentForms: ['마셔요', '마신다', '마셔'],
    futureStems: ['마실 거'],
    en: { past: 'drank', present: 'drink', base: 'drink' },
    ja: { past: '飲みました', present: '飲みます' },
    frame: 'transitive',
  },
  {
    id: 'meet',
    ko: '만나다',
    pastStem: '만났',
    presentForms: ['만나요', '만난다', '만나'],
    futureStems: ['만날 거', '만나려고'],
    en: { past: 'met', present: 'meet', base: 'meet' },
    ja: { past: '会いました', present: '会います' },
    frame: 'meet',
  },
  {
    id: 'watch',
    ko: '보다',
    pastStem: '봤',
    presentForms: ['봐요', '본다', '봐'],
    futureStems: ['볼 거', '보려고'],
    en: { past: 'watched', present: 'watch', base: 'watch' },
    ja: { past: '見ました', present: '見ます' },
    frame: 'transitive',
  },
  {
    id: 'read',
    ko: '읽다',
    pastStem: '읽었',
    presentForms: ['읽어요', '읽는다', '읽어'],
    futureStems: ['읽을 거'],
    en: { past: 'read', present: 'read', base: 'read' },
    ja: { past: '読みました', present: '読みます' },
    frame: 'transitive',
  },
  {
    id: 'listen',
    ko: '듣다',
    pastStem: '들었',
    presentForms: ['들어요', '듣는다'],
    futureStems: ['들을 거'],
    en: { past: 'listened to', present: 'listen to', base: 'listen to' },
    ja: { past: '聞きました', present: '聞きます' },
    frame: 'transitive',
  },
  {
    id: 'buy',
    ko: '사다',
    pastStem: '샀',
    presentForms: ['사요', '산다'],
    futureStems: ['살 거', '사려고'],
    en: { past: 'bought', present: 'buy', base: 'buy' },
    ja: { past: '買いました', present: '買います' },
    frame: 'transitive',
  },
  {
    id: 'make',
    ko: '만들다',
    pastStem: '만들었',
    presentForms: ['만들어요', '만든다'],
    futureStems: ['만들 거'],
    en: { past: 'made', present: 'make', base: 'make' },
    ja: { past: '作りました', present: '作ります' },
    frame: 'transitive',
  },
  {
    id: 'sleep',
    ko: '자다',
    pastStem: '잤',
    presentForms: ['자요', '잔다'],
    futureStems: ['잘 거'],
    en: { past: 'slept', present: 'sleep', base: 'sleep' },
    ja: { past: '寝ました', present: '寝ます' },
    frame: 'intransitive',
  },
  {
    id: 'wake',
    ko: '일어나다',
    pastStem: '일어났',
    presentForms: ['일어나요', '일어난다'],
    futureStems: ['일어날 거'],
    en: { past: 'woke up', present: 'wake up', base: 'wake up' },
    ja: { past: '起きました', present: '起きます' },
    frame: 'intransitive',
  },
  {
    id: 'walk',
    ko: '걷다',
    pastStem: '걸었',
    presentForms: ['걸어요', '걷는다'],
    futureStems: ['걸을 거'],
    en: { past: 'walked', present: 'walk', base: 'walk' },
    ja: { past: '歩きました', present: '歩きます' },
    frame: 'intransitive',
  },
  {
    id: 'rest',
    ko: '쉬다',
    pastStem: '쉬었',
    presentForms: ['쉬어요', '쉰다'],
    futureStems: ['쉴 거'],
    en: { past: 'rested', present: 'rest', base: 'rest' },
    ja: { past: '休みました', present: '休みます' },
    frame: 'intransitive',
  },
  {
    id: 'laugh',
    ko: '웃다',
    pastStem: '웃었',
    presentForms: ['웃어요', '웃는다'],
    futureStems: ['웃을 거'],
    en: { past: 'laughed', present: 'laugh', base: 'laugh' },
    ja: { past: '笑いました', present: '笑います' },
    frame: 'intransitive',
  },
  {
    id: 'cry',
    ko: '울다',
    pastStem: '울었',
    presentForms: ['울어요', '운다'],
    futureStems: ['울 거'],
    en: { past: 'cried', present: 'cry', base: 'cry' },
    ja: { past: '泣きました', present: '泣きます' },
    frame: 'intransitive',
  },
  {
    id: 'hangout',
    ko: '놀다',
    pastStem: '놀았',
    presentForms: ['놀아요', '논다'],
    futureStems: ['놀 거'],
    en: { past: 'hung out', present: 'hang out', base: 'hang out' },
    ja: { past: '遊びました', present: '遊びます' },
    frame: 'intransitive',
  },
  {
    id: 'wait',
    ko: '기다리다',
    pastStem: '기다렸',
    presentForms: ['기다려요', '기다린다'],
    futureStems: ['기다릴 거'],
    en: { past: 'waited for', present: 'wait for', base: 'wait for' },
    ja: { past: '待ちました', present: '待ちます' },
    frame: 'transitive',
  },
  {
    id: 'finish',
    ko: '끝내다',
    pastStem: '끝냈',
    presentForms: ['끝내요', '끝낸다'],
    futureStems: ['끝낼 거'],
    en: { past: 'finished', present: 'finish', base: 'finish' },
    ja: { past: '終えました', present: '終えます' },
    frame: 'transitive',
  },
  {
    id: 'learn',
    ko: '배우다',
    pastStem: '배웠',
    presentForms: ['배워요', '배운다'],
    futureStems: ['배울 거'],
    en: { past: 'learned', present: 'learn', base: 'learn' },
    ja: { past: '習いました', present: '習います' },
    frame: 'transitive',
  },
  {
    id: 'find',
    ko: '찾다',
    pastStem: '찾았',
    presentForms: ['찾아요', '찾는다'],
    futureStems: ['찾을 거'],
    en: { past: 'looked for', present: 'look for', base: 'look for' },
    ja: { past: '探しました', present: '探します' },
    frame: 'transitive',
  },
  {
    id: 'like',
    ko: '좋아하다',
    pastStem: '좋아했',
    presentForms: ['좋아해요', '좋아한다', '좋아해'],
    futureStems: ['좋아할 거'],
    en: { past: 'liked', present: 'like', base: 'like' },
    ja: { past: '好きでした', present: '好きです' },
    frame: 'transitive',
  },
  {
    id: 'send',
    ko: '보내다',
    pastStem: '보냈',
    presentForms: ['보내요', '보낸다'],
    futureStems: ['보낼 거'],
    en: { past: 'sent', present: 'send', base: 'send' },
    ja: { past: '送りました', present: '送ります' },
    frame: 'transitive',
  },
  {
    id: 'take-photo',
    ko: '찍다',
    pastStem: '찍었',
    presentForms: ['찍어요', '찍는다'],
    futureStems: ['찍을 거'],
    en: { past: 'took', present: 'take', base: 'take' },
    ja: { past: '撮りました', present: '撮ります' },
    frame: 'transitive',
  },
  {
    id: 'wash',
    ko: '씻다',
    pastStem: '씻었',
    presentForms: ['씻어요', '씻는다'],
    futureStems: ['씻을 거'],
    en: { past: 'washed up', present: 'wash up', base: 'wash up' },
    ja: { past: '洗いました', present: '洗います' },
    frame: 'intransitive',
  },
  {
    id: 'arrive',
    ko: '도착하다',
    pastStem: '도착했',
    presentForms: ['도착해요', '도착한다'],
    futureStems: ['도착할 거'],
    en: { past: 'arrived', present: 'arrive', base: 'arrive' },
    ja: { past: '着きました', present: '着きます' },
    frame: 'intransitive',
  },
  {
    id: 'scolded',
    ko: '혼나다',
    pastStem: '혼났',
    presentForms: ['혼나요'],
    futureStems: ['혼날 거'],
    en: { past: 'got in trouble', present: 'get in trouble', base: 'get in trouble' },
    ja: { past: '怒られました', present: '怒られます' },
    frame: 'intransitive',
  },
  {
    // '하다'는 마지막에 둔다. '운동했어'는 명사+하다 표(DO_VERBS)가 먼저 잡아야 한다.
    id: 'do',
    ko: '하다',
    pastStem: '했',
    presentForms: ['해요', '한다'],
    futureStems: ['할 거'],
    en: { past: 'did', present: 'do', base: 'do' },
    ja: { past: 'しました', present: 'します' },
    frame: 'transitive',
  },
  {
    id: 'start',
    ko: '시작하다',
    pastStem: '시작했',
    presentForms: ['시작해요', '시작한다'],
    futureStems: ['시작할 거'],
    en: { past: 'started', present: 'start', base: 'start' },
    ja: { past: '始めました', present: '始めます' },
    frame: 'transitive',
  },
];

/**
 * '명사 + 하다' 동사 (공부했어 / 운동했어 …).
 *
 * 하다 동사는 앞의 명사만 갈아 끼우면 되므로 따로 둔다. 여기 있는 명사는
 * '했/해요/한다' 앞에 붙어 있을 때만 동사로 본다.
 */
export const DO_VERBS: { ko: string; en: { past: string; present: string }; ja: { past: string; present: string } }[] = [
  { ko: '공부', en: { past: 'studied', present: 'study' }, ja: { past: '勉強しました', present: '勉強します' } },
  { ko: '운동', en: { past: 'worked out', present: 'work out' }, ja: { past: '運動しました', present: '運動します' } },
  { ko: '일', en: { past: 'worked', present: 'work' }, ja: { past: '仕事しました', present: '仕事します' } },
  { ko: '요리', en: { past: 'cooked', present: 'cook' }, ja: { past: '料理しました', present: '料理します' } },
  { ko: '청소', en: { past: 'cleaned', present: 'clean' }, ja: { past: '掃除しました', present: '掃除します' } },
  { ko: '빨래', en: { past: 'did the laundry', present: 'do the laundry' }, ja: { past: '洗濯しました', present: '洗濯します' } },
  { ko: '산책', en: { past: 'took a walk', present: 'take a walk' }, ja: { past: '散歩しました', present: '散歩します' } },
  { ko: '전화', en: { past: 'made a call', present: 'make a call' }, ja: { past: '電話しました', present: '電話します' } },
  { ko: '이야기', en: { past: 'talked', present: 'talk' }, ja: { past: '話しました', present: '話します' } },
  { ko: '얘기', en: { past: 'talked', present: 'talk' }, ja: { past: '話しました', present: '話します' } },
  { ko: '쇼핑', en: { past: 'went shopping', present: 'go shopping' }, ja: { past: '買い物しました', present: '買い物します' } },
  { ko: '운전', en: { past: 'drove', present: 'drive' }, ja: { past: '運転しました', present: '運転します' } },
  { ko: '연습', en: { past: 'practiced', present: 'practice' }, ja: { past: '練習しました', present: '練習します' } },
  { ko: '준비', en: { past: 'got ready', present: 'get ready' }, ja: { past: '準備しました', present: '準備します' } },
  { ko: '생각', en: { past: 'thought about it', present: 'think about it' }, ja: { past: '考えました', present: '考えます' } },
];

/**
 * 형용사의 ja는 **정중한 과거형 한 덩어리**로 적는다 (疲れました / 楽しかったです).
 * 일본어는 형용사 종류(い·な)마다 과거형이 달라서, 어간만 두고 조합하려 하면 틀린다.
 */
const adj = (ko: string, forms: string[], en: string, ja: string, subject: KoAdjective['subject'] = 'i'): KoAdjective => ({
  ko,
  forms,
  en,
  ja,
  subject,
});

export const ADJECTIVES: KoAdjective[] = [
  adj('피곤하다', ['피곤해요', '피곤했어요', '피곤했어', '피곤해', '피곤하다', '피곤했다'], 'tired', '疲れました'),
  adj('행복하다', ['행복해요', '행복했어요', '행복했어', '행복해', '행복하다'], 'happy', '幸せでした'),
  adj('슬프다', ['슬퍼요', '슬펐어요', '슬펐어', '슬퍼', '슬프다'], 'sad', '悲しかったです'),
  adj('기쁘다', ['기뻐요', '기뻤어요', '기뻤어', '기뻐'], 'glad', 'うれしかったです'),
  adj('신나다', ['신나요', '신났어요', '신났어', '신나'], 'excited', 'わくわくしました'),
  adj('화나다', ['화나요', '화났어요', '화났어', '화나'], 'upset', '怒りました'),
  adj('긴장되다', ['긴장돼요', '긴장됐어요', '긴장됐어', '긴장돼'], 'nervous', '緊張しました'),
  adj('바쁘다', ['바빠요', '바빴어요', '바빴어', '바빠', '바쁘다'], 'busy', '忙しかったです'),
  adj('심심하다', ['심심해요', '심심했어요', '심심했어', '심심해'], 'bored', '退屈でした'),
  adj('배고프다', ['배고파요', '배고팠어요', '배고팠어', '배고파'], 'hungry', 'お腹がすきました'),
  adj('괜찮다', ['괜찮아요', '괜찮았어요', '괜찮았어', '괜찮아'], 'okay', '大丈夫でした'),
  adj('힘들다', ['힘들어요', '힘들었어요', '힘들었어', '힘들어', '힘들다'], 'hard', '大変でした', 'it'),
  adj('좋다', ['좋아요', '좋았어요', '좋았어', '좋아', '좋다'], 'good', 'よかったです', 'it'),
  adj('재미있다', ['재미있어요', '재미있었어요', '재밌었어', '재밌어', '재미있어', '재미있다'], 'fun', '楽しかったです', 'it'),
  adj('맛있다', ['맛있어요', '맛있었어요', '맛있었어', '맛있어', '맛있다'], 'delicious', 'おいしかったです', 'it'),
  adj('덥다', ['더워요', '더웠어요', '더웠어', '더워', '덥다'], 'hot', '暑かったです', 'it'),
  adj('춥다', ['추워요', '추웠어요', '추웠어', '추워', '춥다'], 'cold', '寒かったです', 'it'),
  adj('어렵다', ['어려워요', '어려웠어요', '어려웠어', '어려워'], 'difficult', '難しかったです', 'it'),
  adj('쉽다', ['쉬워요', '쉬웠어요', '쉬웠어', '쉬워'], 'easy', '簡単でした', 'it'),
  adj('예쁘다', ['예뻐요', '예뻤어요', '예뻤어', '예뻐'], 'pretty', 'きれいでした', 'it'),
  adj('조용하다', ['조용해요', '조용했어요', '조용했어', '조용해'], 'quiet', '静かでした', 'it'),
  adj('시끄럽다', ['시끄러워요', '시끄러웠어요', '시끄러웠어', '시끄러워'], 'noisy', 'うるさかったです', 'it'),
];
